/* eslint-disable */
// Generated by scripts/generate-eldritch-implicit-metadata.mjs.
// Sources: RePoE PoE 1 mods and the official PoE 1 trade-stat API.
// Do not edit this file by hand.

export type EldritchImplicitInfluence = 'searing-exarch' | 'eater-of-worlds'

export interface EldritchImplicitMetadata {
  influence: EldritchImplicitInfluence
  tiers: Record<string, number[]>
}

export const ELDRITCH_IMPLICIT_METADATA: Record<string, EldritchImplicitMetadata> = {
  "implicit.stat_1004011302": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_1011760251": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ],
      "2,2": [
        3,
        4,
        5,
        6
      ],
      "3,3": [
        5,
        6
      ]
    }
  },
  "implicit.stat_1065909420": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_1133016593": {
    "influence": "searing-exarch",
    "tiers": {
      "10,13;20,23": [
        1
      ],
      "10,14;21,25": [
        2
      ],
      "11,15;24,27": [
        3
      ],
      "13,16;26,30": [
        4
      ],
      "14,18;29,33": [
        5
      ],
      "15,20;32,36": [
        6
      ]
    }
  },
  "implicit.stat_1134560807": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_114734841": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_118398748": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        3
      ],
      "11,11": [
        4
      ],
      "12,12": [
        5
      ],
      "13,13": [
        6
      ],
      "8,8": [
        1
      ],
      "9,9": [
        2
      ]
    }
  },
  "implicit.stat_1193283913": {
    "influence": "searing-exarch",
    "tiers": {
      "2,2": [
        5,
        6
      ]
    }
  },
  "implicit.stat_1234687045": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_1240056437": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_1269219558": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_1301765461": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2
      ],
      "2,2": [
        3,
        4
      ],
      "3,3": [
        5,
        6
      ]
    }
  },
  "implicit.stat_1310194496": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_1314617696": {
    "influence": "searing-exarch",
    "tiers": {
      "11,13": [
        3
      ],
      "14,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "5,7": [
        1
      ],
      "8,10": [
        2
      ]
    }
  },
  "implicit.stat_1316278494": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,16": [
        1
      ],
      "17,18": [
        2
      ],
      "19,20": [
        3
      ],
      "21,22": [
        4
      ],
      "23,24": [
        5
      ],
      "25,26": [
        6
      ]
    }
  },
  "implicit.stat_1335054179": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_1443060084": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_1443215722": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_1444556985": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        2
      ],
      "12,13": [
        3
      ],
      "14,15": [
        4
      ],
      "16,17": [
        5
      ],
      "18,19": [
        6
      ],
      "8,9": [
        1
      ]
    }
  },
  "implicit.stat_1510714129": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_1514829491": {
    "influence": "searing-exarch",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_1533563525": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1
      ],
      "15,15": [
        2
      ],
      "20,20": [
        3
      ],
      "25,25": [
        4
      ],
      "30,30": [
        5
      ],
      "35,35": [
        6
      ]
    }
  },
  "implicit.stat_1538773178": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_1569101201": {
    "influence": "eater-of-worlds",
    "tiers": {
      "20,22": [
        1
      ],
      "23,25": [
        2
      ],
      "26,28": [
        3
      ],
      "29,31": [
        4
      ],
      "32,33": [
        5
      ],
      "34,35": [
        6
      ]
    }
  },
  "implicit.stat_1571797746": {
    "influence": "eater-of-worlds",
    "tiers": {
      "45,45": [
        1
      ],
      "50,50": [
        2
      ],
      "55,55": [
        3
      ],
      "60,60": [
        4
      ],
      "65,65": [
        5
      ],
      "70,70": [
        6
      ]
    }
  },
  "implicit.stat_1573130764": {
    "influence": "searing-exarch",
    "tiers": {
      "10,13;21,24": [
        6
      ],
      "6,8;13,15": [
        1
      ],
      "7,9;14,16": [
        2
      ],
      "8,10;15,18": [
        3
      ],
      "8,11;17,20": [
        4
      ],
      "9,12;19,22": [
        5
      ]
    }
  },
  "implicit.stat_1585769763": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_1589917703": {
    "influence": "searing-exarch",
    "tiers": {
      "14,16": [
        1
      ],
      "17,19": [
        2
      ],
      "20,22": [
        3
      ],
      "23,25": [
        4
      ],
      "26,27": [
        5
      ],
      "28,29": [
        6
      ]
    }
  },
  "implicit.stat_1592278124": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_1618589784": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_1640259660": {
    "influence": "searing-exarch",
    "tiers": {
      "": [
        4
      ]
    }
  },
  "implicit.stat_1648511635": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_1661253443": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ]
    }
  },
  "implicit.stat_1662974426": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_1671376347": {
    "influence": "searing-exarch",
    "tiers": {
      "13,14": [
        1
      ],
      "15,16": [
        2
      ],
      "17,18": [
        3
      ],
      "19,20": [
        4
      ],
      "21,22": [
        5
      ],
      "23,24": [
        6
      ]
    }
  },
  "implicit.stat_1742651309": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_1743742391": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_174664100": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        1
      ],
      "13,14": [
        2
      ],
      "15,16": [
        3
      ],
      "17,18": [
        4
      ],
      "19,20": [
        5
      ],
      "21,22": [
        6
      ]
    }
  },
  "implicit.stat_1754445556": {
    "influence": "searing-exarch",
    "tiers": {
      "1,2;22,24": [
        1
      ],
      "1,3;24,26": [
        2
      ],
      "1,3;27,28": [
        3
      ],
      "1,3;29,32": [
        4
      ],
      "2,4;32,35": [
        5
      ],
      "2,4;36,38": [
        6
      ]
    }
  },
  "implicit.stat_1783006896": {
    "influence": "searing-exarch",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_1801289192": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_1862926389": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_1871056256": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1,
        2
      ],
      "11,11": [
        3,
        4
      ],
      "12,12": [
        5,
        6
      ],
      "6,6": [
        1,
        2
      ],
      "7,7": [
        3,
        4
      ],
      "8,8": [
        5,
        6
      ]
    }
  },
  "implicit.stat_1871491972": {
    "influence": "eater-of-worlds",
    "tiers": {
      "180,180": [
        6
      ],
      "190,190": [
        5
      ],
      "200,200": [
        4
      ],
      "210,210": [
        3
      ],
      "220,220": [
        2
      ],
      "230,230": [
        1
      ]
    }
  },
  "implicit.stat_1871765599": {
    "influence": "searing-exarch",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_1880071428": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        2
      ],
      "13,14": [
        3
      ],
      "15,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "9,10": [
        1
      ]
    }
  },
  "implicit.stat_1896971621": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        3
      ],
      "11,11": [
        4
      ],
      "12,12": [
        5
      ],
      "13,13": [
        6
      ],
      "8,8": [
        1
      ],
      "9,9": [
        2
      ]
    }
  },
  "implicit.stat_1923879260": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_1944316218": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_1950806024": {
    "influence": "searing-exarch",
    "tiers": {
      "11,13": [
        3
      ],
      "14,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "5,7": [
        1
      ],
      "8,10": [
        2
      ]
    }
  },
  "implicit.stat_1997664024": {
    "influence": "searing-exarch",
    "tiers": {
      "2,2": [
        1
      ],
      "3,3": [
        2
      ],
      "4,4": [
        3
      ],
      "5,5": [
        4
      ],
      "6,6": [
        5
      ],
      "7,7": [
        6
      ]
    }
  },
  "implicit.stat_2034658008": {
    "influence": "searing-exarch",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2062174346": {
    "influence": "eater-of-worlds",
    "tiers": {}
  },
  "implicit.stat_2067062068": {
    "influence": "eater-of-worlds",
    "tiers": {
      "2,2": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2089652545": {
    "influence": "searing-exarch",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_2106365538": {
    "influence": "eater-of-worlds",
    "tiers": {
      "17,18": [
        1
      ],
      "19,20": [
        2
      ],
      "21,22": [
        3
      ],
      "23,24": [
        4
      ],
      "25,26": [
        5
      ],
      "27,28": [
        6
      ]
    }
  },
  "implicit.stat_2109043683": {
    "influence": "searing-exarch",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_2126027382": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_2133341901": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1
      ],
      "15,15": [
        2
      ],
      "20,20": [
        3
      ],
      "25,25": [
        4
      ],
      "30,30": [
        5
      ],
      "35,35": [
        6
      ]
    }
  },
  "implicit.stat_2146663823": {
    "influence": "eater-of-worlds",
    "tiers": {
      "20,22": [
        1
      ],
      "23,25": [
        2
      ],
      "26,28": [
        3
      ],
      "29,31": [
        4
      ],
      "32,33": [
        5
      ],
      "34,35": [
        6
      ]
    }
  },
  "implicit.stat_2154349925": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_2160282525": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_2181791238": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_219391121": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2194114101": {
    "influence": "searing-exarch",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_2231156303": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_2238792070": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_2250111474": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_2250533757": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_2284801675": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_2300399854": {
    "influence": "searing-exarch",
    "tiers": {
      "10,13;20,23": [
        4
      ],
      "10,14;21,25": [
        5
      ],
      "11,15;24,27": [
        6
      ],
      "7,10;15,17": [
        1
      ],
      "8,10;16,19": [
        2
      ],
      "9,11;18,20": [
        3
      ]
    }
  },
  "implicit.stat_2308278768": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_2309614417": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_2339757871": {
    "influence": "eater-of-worlds",
    "tiers": {
      "21,21": [
        1
      ],
      "22,22": [
        2
      ],
      "23,23": [
        3
      ],
      "24,24": [
        4
      ],
      "25,25": [
        5
      ],
      "26,26": [
        6
      ]
    }
  },
  "implicit.stat_2353576063": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_240857668": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_2419712247": {
    "influence": "eater-of-worlds",
    "tiers": {
      "13,14": [
        1
      ],
      "15,16": [
        2
      ],
      "17,18": [
        3
      ],
      "19,20": [
        4
      ],
      "21,22": [
        5
      ],
      "23,24": [
        6
      ]
    }
  },
  "implicit.stat_2420972973": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_2426838124": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_2435536961": {
    "influence": "searing-exarch",
    "tiers": {
      "10,13;21,24": [
        4
      ],
      "11,15;23,26": [
        5
      ],
      "13,16;25,29": [
        6
      ],
      "8,10;15,18": [
        1
      ],
      "8,11;17,20": [
        2
      ],
      "9,12;19,22": [
        3
      ]
    }
  },
  "implicit.stat_2443492284": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_2459451600": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_2467518140": {
    "influence": "eater-of-worlds",
    "tiers": {
      "45,45": [
        1
      ],
      "50,50": [
        2
      ],
      "55,55": [
        3
      ],
      "60,60": [
        4
      ],
      "65,65": [
        5
      ],
      "70,70": [
        6
      ]
    }
  },
  "implicit.stat_2469416729": {
    "influence": "searing-exarch",
    "tiers": {
      "10,12;19,22": [
        2
      ],
      "10,14;21,24": [
        3
      ],
      "11,15;23,27": [
        4
      ],
      "13,16;25,30": [
        5
      ],
      "14,18;28,32": [
        6
      ],
      "9,11;17,20": [
        1
      ]
    }
  },
  "implicit.stat_2482852589": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_2508100173": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_2510655429": {
    "influence": "eater-of-worlds",
    "tiers": {
      "45,45": [
        1
      ],
      "50,50": [
        2
      ],
      "55,55": [
        3
      ],
      "60,60": [
        4
      ],
      "65,65": [
        5
      ],
      "70,70": [
        6
      ]
    }
  },
  "implicit.stat_2527931375": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_2530372417": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_2539726203": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_2555092341": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        6
      ],
      "11,11": [
        5
      ],
      "12,12": [
        4
      ],
      "13,13": [
        3
      ],
      "14,14": [
        2
      ],
      "15,15": [
        1
      ]
    }
  },
  "implicit.stat_2572910724": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_2653955271": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2662416009": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_2676601655": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ],
      "2,2": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2696663331": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_269930125": {
    "influence": "searing-exarch",
    "tiers": {
      "31,33": [
        1
      ],
      "34,36": [
        2
      ],
      "37,39": [
        3
      ],
      "40,42": [
        4
      ],
      "43,45": [
        5
      ],
      "46,48": [
        6
      ]
    }
  },
  "implicit.stat_2705185939": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_274716455": {
    "influence": "searing-exarch",
    "tiers": {
      "20,21": [
        1
      ],
      "22,23": [
        2
      ],
      "24,25": [
        3
      ],
      "26,27": [
        4
      ],
      "28,29": [
        5
      ],
      "30,31": [
        6
      ]
    }
  },
  "implicit.stat_2802161115": {
    "influence": "searing-exarch",
    "tiers": {}
  },
  "implicit.stat_280731498": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_282417259": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_2831165374": {
    "influence": "searing-exarch",
    "tiers": {
      "2,4;34,36": [
        1
      ],
      "2,4;37,40": [
        2
      ],
      "2,4;41,44": [
        3
      ],
      "2,5;45,48": [
        4
      ],
      "2,5;50,53": [
        5
      ],
      "2,6;54,59": [
        6
      ]
    }
  },
  "implicit.stat_2839577586": {
    "influence": "eater-of-worlds",
    "tiers": {
      "30,34": [
        1
      ],
      "35,38": [
        2
      ],
      "39,42": [
        3
      ],
      "43,45": [
        4
      ],
      "46,48": [
        5
      ],
      "49,50": [
        6
      ]
    }
  },
  "implicit.stat_2843214518": {
    "influence": "eater-of-worlds",
    "tiers": {
      "14,16": [
        1
      ],
      "17,19": [
        2
      ],
      "20,22": [
        3
      ],
      "23,25": [
        4
      ],
      "26,27": [
        5
      ],
      "28,29": [
        6
      ]
    }
  },
  "implicit.stat_2844206732": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_2847548062": {
    "influence": "eater-of-worlds",
    "tiers": {
      "5,5": [
        1,
        2,
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2859471749": {
    "influence": "searing-exarch",
    "tiers": {
      "20,19": [
        1
      ],
      "22,21": [
        2
      ],
      "24,23": [
        3
      ],
      "26,25": [
        4
      ],
      "28,27": [
        5
      ],
      "30,29": [
        6
      ]
    }
  },
  "implicit.stat_2866361420": {
    "influence": "eater-of-worlds",
    "tiers": {
      "17,18": [
        1
      ],
      "19,20": [
        2
      ],
      "21,22": [
        3
      ],
      "23,24": [
        4
      ],
      "25,26": [
        5
      ],
      "27,28": [
        6
      ]
    }
  },
  "implicit.stat_2874488491": {
    "influence": "eater-of-worlds",
    "tiers": {
      "180,180": [
        6
      ],
      "190,190": [
        5
      ],
      "200,200": [
        4
      ],
      "210,210": [
        3
      ],
      "220,220": [
        2
      ],
      "230,230": [
        1
      ]
    }
  },
  "implicit.stat_2878959938": {
    "influence": "searing-exarch",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2891184298": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        3
      ],
      "11,11": [
        4
      ],
      "12,12": [
        5
      ],
      "13,13": [
        6
      ],
      "8,8": [
        1
      ],
      "9,9": [
        2
      ]
    }
  },
  "implicit.stat_2901986750": {
    "influence": "eater-of-worlds",
    "tiers": {
      "11,12": [
        4
      ],
      "13,14": [
        5
      ],
      "15,16": [
        6
      ],
      "5,6": [
        1
      ],
      "7,8": [
        2
      ],
      "9,10": [
        3
      ]
    }
  },
  "implicit.stat_2902845638": {
    "influence": "eater-of-worlds",
    "tiers": {
      "2,2": [
        5,
        6
      ]
    }
  },
  "implicit.stat_2907156609": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_2923486259": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_2970621759": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_2974417149": {
    "influence": "eater-of-worlds",
    "tiers": {
      "14,16": [
        1
      ],
      "17,19": [
        2
      ],
      "20,22": [
        3
      ],
      "23,25": [
        4
      ],
      "26,27": [
        5
      ],
      "28,29": [
        6
      ]
    }
  },
  "implicit.stat_3002506763": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_3005472710": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_3015437071": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_3032590688": {
    "influence": "searing-exarch",
    "tiers": {
      "3,5;7,9": [
        1
      ],
      "4,5;8,9": [
        2
      ],
      "4,6;9,10": [
        3
      ],
      "5,6;10,11": [
        4
      ],
      "5,7;11,12": [
        5
      ],
      "6,7;12,14": [
        6
      ]
    }
  },
  "implicit.stat_3037553757": {
    "influence": "searing-exarch",
    "tiers": {
      "19,20": [
        1
      ],
      "21,22": [
        2
      ],
      "23,24": [
        3
      ],
      "25,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_3126680545": {
    "influence": "eater-of-worlds",
    "tiers": {
      "43,45": [
        1
      ],
      "46,48": [
        2
      ],
      "49,51": [
        3
      ],
      "52,54": [
        4
      ],
      "55,57": [
        5
      ],
      "58,60": [
        6
      ]
    }
  },
  "implicit.stat_3151397056": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_3185156108": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_3191479793": {
    "influence": "searing-exarch",
    "tiers": {
      "13,14": [
        1
      ],
      "15,16": [
        2
      ],
      "17,18": [
        3
      ],
      "19,20": [
        4
      ],
      "21,22": [
        5
      ],
      "23,24": [
        6
      ]
    }
  },
  "implicit.stat_3240073117": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_3240769289": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1
      ],
      "15,15": [
        2
      ],
      "20,20": [
        3
      ],
      "25,25": [
        4
      ],
      "30,30": [
        5
      ],
      "35,35": [
        6
      ]
    }
  },
  "implicit.stat_3252913608": {
    "influence": "eater-of-worlds",
    "tiers": {
      "20,22": [
        1
      ],
      "23,25": [
        2
      ],
      "26,28": [
        3
      ],
      "29,31": [
        4
      ],
      "32,33": [
        5
      ],
      "34,35": [
        6
      ]
    }
  },
  "implicit.stat_3291658075": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_3293830776": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_3319896421": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3342989455": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1,
        2
      ],
      "11,11": [
        3,
        4
      ],
      "12,12": [
        5,
        6
      ],
      "6,6": [
        1,
        2
      ],
      "7,7": [
        3,
        4
      ],
      "8,8": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3348324479": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_3372524247": {
    "influence": "searing-exarch",
    "tiers": {
      "13,14": [
        1
      ],
      "15,16": [
        2
      ],
      "17,18": [
        3
      ],
      "19,20": [
        4
      ],
      "21,22": [
        5
      ],
      "23,24": [
        6
      ]
    }
  },
  "implicit.stat_3374165039": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_3377888098": {
    "influence": "eater-of-worlds",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_3382807662": {
    "influence": "searing-exarch",
    "tiers": {
      "11,13": [
        3
      ],
      "14,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "5,7": [
        1
      ],
      "8,10": [
        2
      ]
    }
  },
  "implicit.stat_3395908304": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_3417711605": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_342670903": {
    "influence": "eater-of-worlds",
    "tiers": {
      "3,3": [
        1,
        2,
        3,
        4
      ],
      "4,4": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3456379680": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_3513180117": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_3515686789": {
    "influence": "searing-exarch",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3533655459": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        6
      ],
      "11,11": [
        5
      ],
      "12,12": [
        4
      ],
      "13,13": [
        3
      ],
      "14,14": [
        2
      ],
      "15,15": [
        1
      ]
    }
  },
  "implicit.stat_3541970927": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_3544391750": {
    "influence": "searing-exarch",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_3617955571": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_3637727672": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_3653400807": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_3676141501": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ],
      "2,2": [
        3,
        4,
        5,
        6
      ],
      "3,3": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3679418014": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_3680664274": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_369494213": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_3714003708": {
    "influence": "searing-exarch",
    "tiers": {
      "20,21": [
        1
      ],
      "22,23": [
        2
      ],
      "24,25": [
        3
      ],
      "26,27": [
        4
      ],
      "28,29": [
        5
      ],
      "30,31": [
        6
      ]
    }
  },
  "implicit.stat_3739863694": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_3742945352": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_3764265320": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_3801067695": {
    "influence": "eater-of-worlds",
    "tiers": {
      "35,33": [
        1
      ],
      "38,36": [
        2
      ],
      "41,39": [
        3
      ],
      "44,42": [
        4
      ],
      "47,45": [
        5
      ],
      "50,48": [
        6
      ]
    }
  },
  "implicit.stat_3801128794": {
    "influence": "eater-of-worlds",
    "tiers": {}
  },
  "implicit.stat_3814686091": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_3828375170": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_3848282610": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_3903907406": {
    "influence": "eater-of-worlds",
    "tiers": {
      "67,65": [
        1
      ],
      "70,68": [
        2
      ],
      "73,71": [
        3
      ],
      "76,74": [
        4
      ],
      "79,77": [
        5
      ],
      "82,80": [
        6
      ]
    }
  },
  "implicit.stat_3906868545": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        6
      ],
      "11,11": [
        5
      ],
      "12,12": [
        4
      ],
      "13,13": [
        3
      ],
      "14,14": [
        2
      ],
      "15,15": [
        1
      ]
    }
  },
  "implicit.stat_3948776386": {
    "influence": "eater-of-worlds",
    "tiers": {}
  },
  "implicit.stat_3962278098": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_396238230": {
    "influence": "searing-exarch",
    "tiers": {
      "2,2": [
        1
      ],
      "3,3": [
        2
      ],
      "4,4": [
        3
      ],
      "5,5": [
        4
      ],
      "6,6": [
        5
      ],
      "7,7": [
        6
      ]
    }
  },
  "implicit.stat_3966666111": {
    "influence": "eater-of-worlds",
    "tiers": {
      "3,3": [
        1,
        2,
        3,
        4
      ],
      "4,4": [
        5,
        6
      ]
    }
  },
  "implicit.stat_397427740": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_3995612171": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_3999401129": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_4021566756": {
    "influence": "searing-exarch",
    "tiers": {
      "11,12": [
        3
      ],
      "13,14": [
        4
      ],
      "15,16": [
        5
      ],
      "17,18": [
        6
      ],
      "7,8": [
        1
      ],
      "9,10": [
        2
      ]
    }
  },
  "implicit.stat_4053951709": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_4055307827": {
    "influence": "searing-exarch",
    "tiers": {
      "11,13": [
        3
      ],
      "14,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "5,7": [
        1
      ],
      "8,10": [
        2
      ]
    }
  },
  "implicit.stat_4067062424": {
    "influence": "searing-exarch",
    "tiers": {
      "6,7;11,13": [
        1
      ],
      "6,8;12,15": [
        2
      ],
      "7,10;15,18": [
        4
      ],
      "7,9;13,16": [
        3
      ],
      "8,11;17,19": [
        5
      ],
      "9,12;18,22": [
        6
      ]
    }
  },
  "implicit.stat_4095671657": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ],
      "2,2": [
        3,
        4,
        5,
        6
      ],
      "3,3": [
        5,
        6
      ]
    }
  },
  "implicit.stat_4096052153": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_4101445926": {
    "influence": "searing-exarch",
    "tiers": {
      "25,26": [
        1
      ],
      "27,28": [
        2
      ],
      "29,30": [
        3
      ],
      "31,32": [
        4
      ],
      "33,34": [
        5
      ],
      "35,36": [
        6
      ]
    }
  },
  "implicit.stat_4129825612": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1,
        2
      ],
      "11,11": [
        3,
        4
      ],
      "12,12": [
        5,
        6
      ],
      "6,6": [
        1,
        2
      ],
      "7,7": [
        3,
        4
      ],
      "8,8": [
        5,
        6
      ]
    }
  },
  "implicit.stat_4147277532": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_4175197580": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_4220027924": {
    "influence": "searing-exarch",
    "tiers": {
      "13,14": [
        1
      ],
      "15,16": [
        2
      ],
      "17,18": [
        3
      ],
      "19,20": [
        4
      ],
      "21,22": [
        5
      ],
      "23,24": [
        6
      ]
    }
  },
  "implicit.stat_4223377453": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        1
      ],
      "11,11": [
        2
      ],
      "12,12": [
        3
      ],
      "13,13": [
        4
      ],
      "14,14": [
        5
      ],
      "15,15": [
        6
      ]
    }
  },
  "implicit.stat_4237190083": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_4247488219": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_425242359": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1,
        2
      ],
      "11,11": [
        3,
        4
      ],
      "12,12": [
        5,
        6
      ],
      "6,6": [
        1,
        2
      ],
      "7,7": [
        3,
        4
      ],
      "8,8": [
        5,
        6
      ]
    }
  },
  "implicit.stat_4262448838": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_4274080377": {
    "influence": "eater-of-worlds",
    "tiers": {
      "3,3": [
        1,
        2,
        3,
        4
      ],
      "4,4": [
        5,
        6
      ]
    }
  },
  "implicit.stat_44972811": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_45589825": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_458438597": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_490098963": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        1
      ],
      "15,15": [
        2
      ],
      "20,20": [
        3
      ],
      "25,25": [
        4
      ],
      "30,30": [
        5
      ],
      "35,35": [
        6
      ]
    }
  },
  "implicit.stat_49183689": {
    "influence": "searing-exarch",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_492027537": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_561307714": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        6
      ],
      "5,5": [
        1
      ],
      "6,6": [
        2
      ],
      "7,7": [
        3
      ],
      "8,8": [
        4
      ],
      "9,9": [
        5
      ]
    }
  },
  "implicit.stat_569299859": {
    "influence": "searing-exarch",
    "tiers": {
      "1,1": [
        1,
        2,
        3,
        4
      ],
      "2,2": [
        5,
        6
      ]
    }
  },
  "implicit.stat_623823763": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_624954515": {
    "influence": "eater-of-worlds",
    "tiers": {
      "11,12": [
        2
      ],
      "13,14": [
        3
      ],
      "15,16": [
        4
      ],
      "17,18": [
        5
      ],
      "19,20": [
        6
      ],
      "9,10": [
        1
      ]
    }
  },
  "implicit.stat_631097842": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_674553446": {
    "influence": "searing-exarch",
    "tiers": {
      "5,6;10,11": [
        1
      ],
      "5,7;11,12": [
        2
      ],
      "6,7;12,14": [
        3
      ],
      "6,9;13,15": [
        4
      ],
      "7,9;14,17": [
        5
      ],
      "8,10;16,18": [
        6
      ]
    }
  },
  "implicit.stat_680068163": {
    "influence": "eater-of-worlds",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_681332047": {
    "influence": "searing-exarch",
    "tiers": {
      "10,10": [
        3
      ],
      "11,11": [
        4
      ],
      "12,12": [
        5
      ],
      "13,13": [
        6
      ],
      "8,8": [
        1
      ],
      "9,9": [
        2
      ]
    }
  },
  "implicit.stat_736967255": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,28": [
        5
      ],
      "29,30": [
        6
      ]
    }
  },
  "implicit.stat_737908626": {
    "influence": "searing-exarch",
    "tiers": {
      "28,30": [
        1
      ],
      "31,33": [
        2
      ],
      "34,36": [
        3
      ],
      "37,39": [
        4
      ],
      "40,42": [
        5
      ],
      "43,45": [
        6
      ]
    }
  },
  "implicit.stat_744082851": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_763611529": {
    "influence": "searing-exarch",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_770672621": {
    "influence": "searing-exarch",
    "tiers": {
      "14,16": [
        1
      ],
      "17,19": [
        2
      ],
      "20,22": [
        3
      ],
      "23,25": [
        4
      ],
      "26,27": [
        5
      ],
      "28,29": [
        6
      ]
    }
  },
  "implicit.stat_782230869": {
    "influence": "eater-of-worlds",
    "tiers": {
      "14,16": [
        1
      ],
      "17,19": [
        2
      ],
      "20,22": [
        3
      ],
      "23,25": [
        4
      ],
      "26,27": [
        5
      ],
      "28,29": [
        6
      ]
    }
  },
  "implicit.stat_788317702": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_789117908": {
    "influence": "eater-of-worlds",
    "tiers": {
      "19,21": [
        1
      ],
      "22,24": [
        2
      ],
      "25,27": [
        3
      ],
      "28,30": [
        4
      ],
      "31,33": [
        5
      ],
      "34,36": [
        6
      ]
    }
  },
  "implicit.stat_78985352": {
    "influence": "searing-exarch",
    "tiers": {
      "15,15": [
        1
      ],
      "20,20": [
        2
      ],
      "25,25": [
        3
      ],
      "30,30": [
        4
      ],
      "35,35": [
        5
      ],
      "40,40": [
        6
      ]
    }
  },
  "implicit.stat_789978501": {
    "influence": "searing-exarch",
    "tiers": {
      "15,17": [
        1
      ],
      "18,20": [
        2
      ],
      "21,23": [
        3
      ],
      "24,26": [
        4
      ],
      "27,29": [
        5
      ],
      "30,32": [
        6
      ]
    }
  },
  "implicit.stat_791154540": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_795138349": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        2
      ],
      "15,15": [
        3
      ],
      "20,20": [
        4
      ],
      "25,25": [
        5
      ],
      "30,30": [
        6
      ],
      "5,5": [
        1
      ]
    }
  },
  "implicit.stat_80079005": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1
      ],
      "0.3,0.3": [
        2
      ],
      "0.4,0.4": [
        3
      ],
      "0.5,0.5": [
        4
      ],
      "0.6,0.6": [
        5
      ],
      "0.7,0.7": [
        6
      ]
    }
  },
  "implicit.stat_803185500": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,11": [
        3
      ],
      "12,13": [
        4
      ],
      "14,15": [
        5
      ],
      "16,17": [
        6
      ],
      "6,7": [
        1
      ],
      "8,9": [
        2
      ]
    }
  },
  "implicit.stat_818778753": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_824762042": {
    "influence": "eater-of-worlds",
    "tiers": {
      "180,180": [
        6
      ],
      "190,190": [
        5
      ],
      "200,200": [
        4
      ],
      "210,210": [
        3
      ],
      "220,220": [
        2
      ],
      "230,230": [
        1
      ]
    }
  },
  "implicit.stat_902747843": {
    "influence": "searing-exarch",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_979246511": {
    "influence": "eater-of-worlds",
    "tiers": {
      "4,4": [
        1,
        2
      ],
      "5,5": [
        3,
        4
      ],
      "6,6": [
        5,
        6
      ]
    }
  },
  "implicit.stat_984148407": {
    "influence": "searing-exarch",
    "tiers": {
      "2,2": [
        1
      ],
      "3,3": [
        2
      ],
      "4,4": [
        3
      ],
      "5,5": [
        4
      ],
      "6,6": [
        5
      ],
      "7,7": [
        6
      ]
    }
  },
  "implicit.stat_986397080": {
    "influence": "eater-of-worlds",
    "tiers": {
      "33,35": [
        1
      ],
      "36,38": [
        2
      ],
      "39,41": [
        3
      ],
      "42,44": [
        4
      ],
      "45,47": [
        5
      ],
      "48,50": [
        6
      ]
    }
  },
  "implicit.stat_988575597": {
    "influence": "eater-of-worlds",
    "tiers": {
      "10,10": [
        4
      ],
      "11,11": [
        5
      ],
      "12,12": [
        6
      ],
      "7,7": [
        1
      ],
      "8,8": [
        2
      ],
      "9,9": [
        3
      ]
    }
  },
  "implicit.stat_989800292": {
    "influence": "eater-of-worlds",
    "tiers": {
      "0.2,0.2": [
        1,
        2,
        3,
        4
      ],
      "0.3,0.3": [
        5,
        6
      ]
    }
  }
}
