import { Stat } from "@/assets/data/interfaces";

export const strengthStat: Stat["tiers"] = {
  explicit: [
    {
      id: "Strength",
      items: {
        sword: 8,
        flail: 8,
        ring: 8,
        sceptre: 8,
        spear: 8,
        body_armour: 8,
        axe: 8,
        mace: 8,
        belt: 9,
        amulet: 8,
        crossbow: 8,
      },
      mods: [
        {
          ilvl: 1,
          id: "Strength1",
          name: "of the Brute",
          values: [[5, 8]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 11,
          id: "Strength2",
          name: "of the Wrestler",
          values: [[9, 12]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 22,
          id: "Strength3",
          name: "of the Bear",
          values: [[13, 16]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 33,
          id: "Strength4",
          name: "of the Lion",
          values: [[17, 20]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 44,
          id: "Strength5",
          name: "of the Gorilla",
          values: [[21, 24]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 55,
          id: "Strength6",
          name: "of the Goliath",
          values: [[25, 27]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 66,
          id: "Strength7",
          name: "of the Leviathan",
          values: [[28, 30]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 74,
          id: "Strength8",
          name: "of the Titan",
          values: [[31, 33]],
          items: [
            "sword",
            "flail",
            "ring",
            "sceptre",
            "spear",
            "body_armour",
            "axe",
            "mace",
            "belt",
            "amulet",
            "crossbow",
          ],
        },
        {
          ilvl: 81,
          id: "Strength9",
          name: "of the Gods",
          values: [[34, 36]],
          items: ["belt"],
        },
      ],
    },
  ],
  implicit: {
    amulet: {
      id: "AmuletImplicitStrength",
      items: {},
      mods: [
        {
          ilvl: 10,
          id: "AmuletImplicitStrength1",
          name: "",
          values: [[10, 15]],
          items: [],
        },
      ],
    },
  },
  unique: {},
  corruption: [
    {
      id: "CorruptionStrength",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionStrength1",
          name: "",
          values: [[10, 15]],
          items: [],
        },
      ],
    },
  ],
  crafted: [
    {
      id: "StrengthCrafted",
      items: {},
      mods: [
        {
          ilvl: 40,
          id: "StrengthCrafted",
          name: "",
          values: [[25, 30]],
          items: [],
        },
      ],
    },
  ],
  jewel: [
    {
      id: "CorruptionJewelStrength",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionJewelStrength1",
          name: "",
          values: [[5, 10]],
          items: [],
        },
      ],
    },
  ],
  corruptionjewel: [],
  uniquejewel: [
    {
      id: "StrengthUniqueJewel",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "StrengthUniqueJewel34",
          name: "",
          values: [[16, 24]],
          items: [],
        },
        {
          ilvl: 1,
          id: "StrengthUniqueJewel37",
          name: "",
          values: [[16, 24]],
          items: [],
        },
      ],
    },
  ],
};

export const maxManaStat: Stat["tiers"] = {
  explicit: [
    {
      id: "IncreasedMana",
      items: {
        ring: 13,
        boots: 12,
        helmet: 12,
        gloves: 12,
        trap: 12,
        sceptre: 12,
        focus: 12,
        wand: 12,
        belt: 12,
        amulet: 13,
      },
      mods: [
        {
          ilvl: 1,
          id: "IncreasedMana1",
          name: "Beryl",
          values: [[10, 14]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 6,
          id: "IncreasedMana2",
          name: "Cobalt",
          values: [[15, 24]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 12,
          id: "IncreasedMana3",
          name: "Azure",
          values: [[25, 34]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 19,
          id: "IncreasedMana4",
          name: "Teal",
          values: [[35, 54]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 25,
          id: "IncreasedMana5",
          name: "Cerulean",
          values: [[55, 64]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 31,
          id: "IncreasedMana6",
          name: "Aqua",
          values: [[65, 79]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 36,
          id: "IncreasedMana7",
          name: "Opalescent",
          values: [[80, 89]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 43,
          id: "IncreasedMana8",
          name: "Gentian",
          values: [[90, 104]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 53,
          id: "IncreasedMana9",
          name: "Chalybeous",
          values: [[105, 124]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 63,
          id: "IncreasedMana10",
          name: "Mazarine",
          values: [[125, 149]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 69,
          id: "IncreasedMana11",
          name: "Blue",
          values: [[150, 164]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 77,
          id: "IncreasedMana12",
          name: "Zaffre",
          values: [[165, 179]],
          items: [
            "ring",
            "boots",
            "helmet",
            "gloves",
            "trap",
            "sceptre",
            "focus",
            "wand",
            "belt",
            "amulet",
          ],
        },
        {
          ilvl: 82,
          id: "IncreasedMana13",
          name: "Ultramarine",
          values: [[180, 189]],
          items: ["ring", "amulet"],
        },
      ],
    },
    {
      id: "IncreasedManaTwoHandWeapon",
      items: {
        staff: 12,
      },
      mods: [
        {
          ilvl: 1,
          id: "IncreasedManaTwoHandWeapon1",
          name: "Beryl",
          values: [[14, 20]],
          items: ["staff"],
        },
        {
          ilvl: 6,
          id: "IncreasedManaTwoHandWeapon2_",
          name: "Cobalt",
          values: [[21, 34]],
          items: ["staff"],
        },
        {
          ilvl: 12,
          id: "IncreasedManaTwoHandWeapon3_",
          name: "Azure",
          values: [[35, 48]],
          items: ["staff"],
        },
        {
          ilvl: 19,
          id: "IncreasedManaTwoHandWeapon4",
          name: "Sapphire",
          values: [[49, 76]],
          items: ["staff"],
        },
        {
          ilvl: 25,
          id: "IncreasedManaTwoHandWeapon5",
          name: "Cerulean",
          values: [[77, 90]],
          items: ["staff"],
        },
        {
          ilvl: 31,
          id: "IncreasedManaTwoHandWeapon6",
          name: "Aqua",
          values: [[91, 111]],
          items: ["staff"],
        },
        {
          ilvl: 36,
          id: "IncreasedManaTwoHandWeapon7",
          name: "Opalescent",
          values: [[112, 125]],
          items: ["staff"],
        },
        {
          ilvl: 43,
          id: "IncreasedManaTwoHandWeapon8_",
          name: "Gentian",
          values: [[126, 146]],
          items: ["staff"],
        },
        {
          ilvl: 53,
          id: "IncreasedManaTwoHandWeapon9",
          name: "Chalybeous",
          values: [[147, 174]],
          items: ["staff"],
        },
        {
          ilvl: 63,
          id: "IncreasedManaTwoHandWeapon10",
          name: "Mazarine",
          values: [[175, 209]],
          items: ["staff"],
        },
        {
          ilvl: 69,
          id: "IncreasedManaTwoHandWeapon11",
          name: "Blue",
          values: [[210, 230]],
          items: ["staff"],
        },
        {
          ilvl: 77,
          id: "IncreasedManaTwoHandWeapon12",
          name: "Zaffre",
          values: [[231, 251]],
          items: ["staff"],
        },
      ],
    },
  ],
  implicit: {
    ring: {
      id: "RingImplicitIncreasedMana",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "RingImplicitIncreasedMana1",
          name: "",
          values: [[20, 30]],
          items: [],
        },
      ],
    },
  },
  unique: {},
  corruption: [
    {
      id: "CorruptionIncreasedMana",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionIncreasedMana1",
          name: "",
          values: [[20, 25]],
          items: [],
        },
      ],
    },
  ],
  crafted: [],
  jewel: [],
  corruptionjewel: [],
  uniquejewel: [],
};

export const addedFireDamageStat: Stat["tiers"] = {
  explicit: [
    {
      id: "LocalAddedFireDamage",
      items: {
        dagger: 10,
        spear: 10,
        axe: 10,
        claw: 10,
        two_hand_weapon: 10,
        sword: 10,
        flail: 10,
        bow: 10,
        mace: 10,
        crossbow: 10,
      },
      mods: [
        {
          ilvl: 1,
          id: "LocalAddedFireDamage1",
          name: "Heated",
          values: [
            [2, 3],
            [4, 5],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 11,
          id: "LocalAddedFireDamage2",
          name: "Smouldering",
          values: [
            [4, 7],
            [8, 11],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 18,
          id: "LocalAddedFireDamage3",
          name: "Smoking",
          values: [
            [7, 11],
            [12, 18],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 26,
          id: "LocalAddedFireDamage4",
          name: "Burning",
          values: [
            [11, 17],
            [18, 26],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 33,
          id: "LocalAddedFireDamage5",
          name: "Flaming",
          values: [
            [14, 21],
            [22, 33],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 42,
          id: "LocalAddedFireDamage6",
          name: "Scorching",
          values: [
            [20, 30],
            [31, 46],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 51,
          id: "LocalAddedFireDamage7",
          name: "Incinerating",
          values: [
            [26, 39],
            [40, 59],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 62,
          id: "LocalAddedFireDamage8",
          name: "Blasting",
          values: [
            [35, 52],
            [53, 79],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 74,
          id: "LocalAddedFireDamage9",
          name: "Cremating",
          values: [
            [45, 67],
            [68, 102],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
        {
          ilvl: 81,
          id: "LocalAddedFireDamage10_",
          name: "Carbonising",
          values: [
            [52, 78],
            [79, 119],
          ],
          items: [
            "sword",
            "flail",
            "dagger",
            "spear",
            "bow",
            "axe",
            "two_hand_weapon",
            "claw",
            "mace",
            "crossbow",
          ],
        },
      ],
    },
    {
      id: "LocalAddedFireDamageTwoHand",
      items: {
        sword: 10,
        one_hand_weapon: 10,
        warstaff: 10,
        axe: 10,
        mace: 10,
      },
      mods: [
        {
          ilvl: 1,
          id: "LocalAddedFireDamageTwoHand1",
          name: "Heated",
          values: [
            [2, 4],
            [5, 7],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 11,
          id: "LocalAddedFireDamageTwoHand2",
          name: "Smouldering",
          values: [
            [6, 10],
            [11, 16],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 18,
          id: "LocalAddedFireDamageTwoHand3",
          name: "Smoking",
          values: [
            [10, 16],
            [17, 25],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 26,
          id: "LocalAddedFireDamageTwoHand4",
          name: "Burning",
          values: [
            [16, 24],
            [25, 37],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 33,
          id: "LocalAddedFireDamageTwoHand5",
          name: "Flaming",
          values: [
            [20, 31],
            [32, 47],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 42,
          id: "LocalAddedFireDamageTwoHand6",
          name: "Scorching",
          values: [
            [28, 43],
            [44, 65],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 51,
          id: "LocalAddedFireDamageTwoHand7",
          name: "Incinerating",
          values: [
            [37, 55],
            [56, 84],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 62,
          id: "LocalAddedFireDamageTwoHand8_",
          name: "Blasting",
          values: [
            [49, 74],
            [75, 113],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 74,
          id: "LocalAddedFireDamageTwoHand9",
          name: "Cremating",
          values: [
            [64, 96],
            [97, 146],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
        {
          ilvl: 81,
          id: "LocalAddedFireDamageTwoHand10",
          name: "Carbonising",
          values: [
            [74, 112],
            [113, 169],
          ],
          items: ["sword", "one_hand_weapon", "warstaff", "axe", "mace"],
        },
      ],
    },
  ],
  implicit: {},
  unique: {},
  corruption: [
    {
      id: "CorruptionLocalAddedFireDamage",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionLocalAddedFireDamage1",
          name: "",
          values: [
            [9, 14],
            [15, 22],
          ],
          items: [],
        },
      ],
    },
    {
      id: "CorruptionLocalAddedFireDamageTwoHand",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionLocalAddedFireDamageTwoHand1",
          name: "",
          values: [
            [13, 20],
            [21, 31],
          ],
          items: [],
        },
      ],
    },
  ],
  crafted: [],
  jewel: [],
  corruptionjewel: [],
  uniquejewel: [],
};

export const gainManaOnKillStat: Stat["tiers"] = {
  explicit: [
    {
      id: "ManaGainedFromEnemyDeath",
      items: {
        ring: 6,
        gloves: 8,
        wand: 8,
        quiver: 6,
        weapon: 8,
        staff: 8,
        trap: 8,
      },
      mods: [
        {
          ilvl: 1,
          id: "ManaGainedFromEnemyDeath1",
          name: "of Absorption",
          values: [[2, 3]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 12,
          id: "ManaGainedFromEnemyDeath2",
          name: "of Osmosis",
          values: [[4, 5]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 23,
          id: "ManaGainedFromEnemyDeath3",
          name: "of Infusion",
          values: [[6, 9]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 34,
          id: "ManaGainedFromEnemyDeath4",
          name: "of Enveloping",
          values: [[10, 14]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 45,
          id: "ManaGainedFromEnemyDeath5",
          name: "of Consumption",
          values: [[15, 20]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 56,
          id: "ManaGainedFromEnemyDeath6",
          name: "of Siphoning",
          values: [[21, 27]],
          items: [
            "ring",
            "gloves",
            "staff",
            "quiver",
            "weapon",
            "wand",
            "trap",
          ],
        },
        {
          ilvl: 67,
          id: "ManaGainedFromEnemyDeath7",
          name: "of Devouring",
          values: [[28, 35]],
          items: ["gloves", "staff", "weapon", "wand", "trap"],
        },
        {
          ilvl: 78,
          id: "ManaGainedFromEnemyDeath8",
          name: "of Assimilation",
          values: [[36, 45]],
          items: ["gloves", "staff", "weapon", "wand", "trap"],
        },
      ],
    },
  ],
  implicit: {
    axe: {
      id: "AxeImplicitManaGainedFromEnemyDeath",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "AxeImplicitManaGainedFromEnemyDeath1",
          name: "",
          values: [[28, 35]],
          items: [],
        },
      ],
    },
  },
  unique: {},
  corruption: [
    {
      id: "CorruptionManaGainedFromEnemyDeath",
      items: {},
      mods: [
        {
          ilvl: 1,
          id: "CorruptionManaGainedFromEnemyDeath1",
          name: "",
          values: [[10, 15]],
          items: [],
        },
      ],
    },
  ],
  crafted: [],
  jewel: [],
  corruptionjewel: [],
  uniquejewel: [],
};
